layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 10
  exclude:
    archived: false
    forks: false
    projects:
     - phui.github.io
     - kcoloring
  include:
    - IUNetSci/BotSlayer-CE
    - phui/tweet_redis
    - phui/twitter_log_pipeline

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: pikmaihui
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: patrick_pmhui
  # unsplash: your_username
  # vk: your_username
  website: http://stuffoverflow.com
  # youtube: your_username

topics:
  - name: BotSlayer
    web_url: https://osome.iuni.iu.edu/tools/botslayer/
    image_url: /assets/botslayer.png

  - name: Bot Electioneering Volume
    web_url: https://botometer.iuni.iu.edu/bev/
    image_url: https://botometer.iuni.iu.edu/bev/static/image/logo.png

  - name: Hoaxy
    web_url: https://hoaxy.iuni.iu.edu/
    image_url: https://osome.iuni.iu.edu/tools/img/hoaxy.png
